name: 🐞 错误报告
description: 当出现问题时提交报告以便修复！
title: '🐞 错误报告: xxx.md'
labels: ['request']
assignees: vipzhicheng
body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧
        注意：https://github.com/jaywcjlove/reference 是源头项目，提交错误建议去那里提交。
        如果您坚持在这里提交，我有时间也会处理，如果您的贡献有价值，我也会考虑 PR 给源项目。
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧

  - type: input
    id: error-list
    attributes:
      label: 📄 错误清单
      description: 指定错误清单文件，方便我们快速定位错误。
      placeholder: ex. `docs/ansible.md`
    validations:
      required: true

  - type: checkboxes
    id: error-type
    attributes:
      label: 🧨 错误类型
      description: 请选择错误类型。
      options:
        - label: 排版 & 文字错误
        - label: 清单内容示例错误
        - label: 其它
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📖 错误说明
      description: 您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的速查表(速查表)。
      placeholder: 请您在这里详细介绍具体错误问题
    validations:
      required: true
