name: 🤙 速查表请求
description: 请求添加速查表和参考
title: '【速查表】 请求: <Name>'
labels: ['request']
assignees: jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧
        注意：https://github.com/jaywcjlove/reference 是源头项目，添加新清单建议去那里提交。
        如果您坚持在这里提交，我有时间也会处理，如果您的贡献有价值，我也会考虑 PR 给源项目。
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧

  - type: textarea
    id: description
    attributes:
      label: 说明项目
      description: 您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的速查表(速查表)。
      placeholder: 【请您在这里介绍一下工具或者语言，这很重要】
    validations:
      required: true

  - type: input
    id: official-website
    attributes:
      label: 提供官网
      description: 提供官网网站有助于我们整理成速查表(速查表)
      placeholder: ex. https://xxx.com

  - type: markdown
    attributes:
      value: |
        _⚠️ 注意: 随着内容越来越多，可能甚至找不到这个工具或者语言的官网，请您在这里提供以便大家共同参与贡献内容_

  - type: textarea
    id: reference-url
    attributes:
      label: 参考资料 URL
      description: 提供更多参考资料有助于我们整理成速查表(速查表)
      placeholder: |
        参考资料 URL
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        _⚠️ 注意: 提供更多参考资料，以便大家共同参与贡献内容_
